# Generated by Django 3.2.7 on 2021-09-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='url',
            new_name='hostname',
        ),
    ]
